[tools]
bun = "latest"
cargo-binstall = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-insta" = "latest"
"cargo:cargo-release" = "latest"
"cargo:git-cliff" = "latest"
"cargo:toml-cli" = "latest"
"cargo:usage-cli" = { version = "latest", os = ["linux", "macos"] }
golang = 'latest'
node = 'latest'
python = "3.11"
ruby = 'latest'
rust = 'latest'
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
experimental = true
